---
# tasks file for ssh_admin_key_service

# Use a custom selinux policy
# to confine all users including root
- name: "Copy ssh key SELinux policy"
  template:
    src: "admin_ssh_add.te.j2"
    dest: "{{ ('/root/admin_ssh_add_' + ssh_admin_key_service_id + '.te') | quote }}"
    owner: "root"
    group: "root"
    mode: "0400"
  become: true

# man audit2allow
- name: "Build selinux ssh key .mod file"
  command: >
    checkmodule -M -m -o
    {{ ('/root/admin_ssh_add_' + ssh_admin_key_service_id + '.mod') | quote }}
    {{ ('/root/admin_ssh_add_' + ssh_admin_key_service_id + '.te') | quote }}
  args:
    creates: "/root/admin_ssh_add.mod"
  become: true

- name: "Build selinux ssh key .pp file"
  command: >
    semodule_package -o \
    {{ ('/root/admin_ssh_add_' + ssh_admin_key_service_id + '.pp') | quote }}
    -m {{ ('/root/admin_ssh_add_' + ssh_admin_key_service_id + '.mod') | quote }}
  args:
    creates: "/root/admin_ssh_add.pp"
  become: true

- name: "Import SELinux module"
  command: "semodule -i {{ ('/root/admin_ssh_add_' + ssh_admin_key_service_id + '.pp') | quote }}"
  become: true

- name: "Remove SELinux modules tmp files"
  file:
    state: "absent"
    path: "{{ item }}"
  become: true
  loop: 
    - "{{ ('/root/admin_ssh_add_' + ssh_admin_key_service_id + '.pp') | quote }}"
    - "{{ ('/root/admin_ssh_add_' + ssh_admin_key_service_id + '.mod') | quote }}"
    - "{{ ('/root/admin_ssh_add_' + ssh_admin_key_service_id + '.te') | quote }}"

- name: "Deploy systemd --user ssh_user_agent service"
  template:
    src: "etc/systemd/user/ssh_user_agent.service"
    dest: "/etc/systemd/user/ssh_user_agent.service"
    owner: "root"
    group: "root"
    mode: "o-xw"
  become: true

- name: "Reload systemd --user"
  systemd:
    scope: 'user'
    daemon_reload: true
  #become: true

- name: "Deploy systemd ssh_add service"
  template:
    src: "etc/systemd/system/admin_ssh_add@.service"
    dest: "/etc/systemd/system/{{ ssh_admin_key_service_name }}@.service"
    owner: "root"
    group: "root"
    mode: "o-xw"
  become: true

- name: "Reload systemd"
  systemd:
    daemon_reload: true
  become: true

- name: "Deploy polkit rule"
  template:
    src: "etc/polkit-1/rules.d/99-ssh_admin_key_service.rules"
    dest: "/etc/polkit-1/rules.d/99-{{ ssh_admin_key_service_name }}.rules"
    owner: "root"
    group: "root"
    mode: "o-xw"
  become: true

- name: "Build .ssh key folder"
  file:
    path: "{{ ssh_admin_key_service_keypath | dirname }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: '0700'
  become: true

# due to selinux rules the only 
# way to edit the ssh key is by 
# deletion and addition 
- name: "Remove the current ssh key"
  file:
    path: "{{ ssh_admin_key_service_keypath }}"
    state: "absent"
  become: true

- name: "Deploy ssh key"
  copy:
    # the key should be store
    # in clear text form
    src: "id_rsa"
    dest: "{{ ssh_admin_key_service_keypath }}"
    owner: "root"
    group: "root"
    mode: '0400'
    setype: "{{ ssh_admin_key_service_setype }}"
  become: true


